Feature-US003-23
dbinclui-org/dbinclui-backend pull request #21
Opened 2021-12-27 18:49 UTC by nickolasL13

2021-12-27 18:53 UTC, arthurvergacas requested changes
gente eu nao sei se coloca o id na interface, já que ela é uma coisa que todo documento na collection tem obrigatoriamente
ai n tenho certeza se é uma boa colocar, se alguem puder confirmar sla

2021-12-27 18:56 UTC, nickolasL13 commented
> 
Mas isso não é o Guide? Tava como critério de aceitação no doc do Maurício

2021-12-27 19:12 UTC, arthurvergacas approved these changes

2021-12-28 12:31 UTC, eduardoaraya approved these changes

2021-12-28 14:11 UTC, brunomdrrosa approved these changes

2021-12-28 17:45 UTC, fabiojcbatista approved these changes

2021-12-28 18:48 UTC, merged