US003 - [Back] - Criar Controller - feat: inserindo post no Controller
dbinclui-org/dbinclui-backend pull request #23
Opened 2021-12-27 20:12 UTC by fabiojcbatista

2021-12-27 20:35 UTC, arthurvergacas requested changes

2021-12-27 20:35 UTC, arthurvergacas commented on src/app/controllers/GuidesController.ts
> +  async postGuides(req: Request, res: Response) {
Será que não era melhor mudar o nome dessa função pra algo como `registerGuide`??

2021-12-27 20:35 UTC, eduardoaraya approved these changes, later dismissed

2021-12-28 12:32 UTC, eduardoaraya approved these changes

2021-12-28 17:21 UTC, arthurvergacas approved these changes
lindissimo!!!!!!!!!!!!!!!!!!!!!!!!! :star:

2021-12-28 18:54 UTC, brunomdrrosa approved these changes

2021-12-28 18:54 UTC, NicoleSF approved these changes

2021-12-28 18:56 UTC, merged