Feature/dbi 32 Definir Paths no tsconfig.json
dbinclui-org/dbinclui-backend pull request #37
Opened 2022-01-03 17:15 UTC by LizSantana

## Descrição

Altera as paths de configuração do tsconfig.json para que no código os imports fiquem visualmente limpos e agradáveis. Houve alteração na configuração no build e no run dev do package.json, o run dev não está mais configurado com o nodemon.

____

**Link do card:**
[[back] - Definir Paths no tsconfig.json](https://trello.com/c/xUF836Qw/32-back-definir-paths-no-tsconfigjson)

____

## Checklist Code Review
Avaliar se todos os itens a seguir foram feitos. Os itens com `*` não são obrigatórios.

- [ ] Foi adicionada a descrição da PR
- [ ] Foi adicionado o link do card
- [ ] A branch segue o padrão com o prefixo DBI
- [ ] Está seguindo os padrões de prefixo do gitflow (feature, bugfix, hotfix, release)
- [ ] O título da PR segue o padrão: ***Nome da branch - Título do card***
- [ ] A PR está sendo enviada para a branch `develop`
- [ ] O Repositório que a PR está sendo enviada é o [**dbinclui-org/dbinclui-backend**](https://github.com/dbinclui-org/dbinclui-backend)
- [ ] Foi realizado os testes unitários *
- [ ] Foi realizado os testes de integração *
- [ ] Foi adicionada as respectivas **labels**
- [ ] A PR foi assinada

2022-01-03 18:52 UTC, eduardoaraya requested changes

2022-01-03 18:52 UTC, eduardoaraya commented on package.json
> +    "start": "node dist/index.js",
Manter o comando: `"start": "node dist/src/index.js"`

2022-01-04 17:02 UTC, eduardoaraya approved these changes

2022-01-04 17:02 UTC, fabiojcbatista approved these changes

2022-01-04 17:10 UTC, brunomdrrosa approved these changes

2022-01-04 17:11 UTC, nickolasL13 approved these changes

2022-01-04 17:11 UTC, merged