Feature/DBI-55-2 - Criação documento/schema "guides"
dbinclui-org/dbinclui-backend pull request #4
Opened 2021-12-16 20:02 UTC by AndersonMoura333

2021-12-16 20:06 UTC, ysncastro approved these changes

2021-12-16 20:11 UTC, arthurvergacas requested changes
Acho q se pa melhor rodar o prettier e o linter primeiro nao??
Só dar pull develop, o .eslintrc.json ja ta la
ai so formatar e show

2021-12-16 21:05 UTC, arthurvergacas approved these changes
LINDISSIMO

2021-12-16 22:33 UTC, DayMendes approved these changes

2021-12-16 22:40 UTC, merged

2021-12-17 12:28 UTC, eduardoaraya commented on src/app/entities/guides.ts
> +export interface Guides{
@AndersonMoura333  @ysncastro 
Ajustar identação e ao invés de utilizar *virgula* deve ser *ponto e virgula*
```
export interface Guides{
  title: string;
  content: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}
```

2021-12-17 12:28 UTC, eduardoaraya commented on src/app/models/modelGuides.ts
> +import {Guides} from '../entities/guides'
Adicionar espaço entre as chaves nas importações:
Exemplo: 
```
import { Guides } from '../entities/guides'
```

2021-12-17 12:31 UTC, eduardoaraya commented on src/app/models/modelGuides.ts
> +export const GuidesModel = model<Guides>('Guides', GuidesSchema, 'guides');
Nomer como apenas `Guides`, e também alterar o nome do arquivo de `modelGuides.ts` para apenas `guides.ts` pos ele já se encontra na pasta models, então não precisa ter o prefixo "model".