Feature/dbi us007 38 - US007 - [Back] - Validação
dbinclui-org/dbinclui-backend pull request #50
Opened 2022-01-11 15:51 UTC by fabiojcbatista

## Descrição

Criação do schema para CategoriesValidator
Criação da função de Validação da Requisição
Criação de testes para Categories.test.ts

____

**Link do card:**
[US007 - [Back] - Validação](https://trello.com/c/u4SQNpuJ/38-4-us007-back-valida%C3%A7%C3%A3o)

____

## Checklist Code Review
Avaliar se todos os itens a seguir foram feitos. Os itens com `*` não são obrigatórios.

- [x] Foi adicionada a descrição da PR
- [x] Foi adicionado o link do card
- [x] A branch segue o padrão com o prefixo DBI
- [x] Está seguindo os padrões de prefixo do gitflow (feature, bugfix, hotfix, release)
- [x] O título da PR segue o padrão: ***Nome da branch - Título do card***
- [x] A PR está sendo enviada para a branch `develop`
- [x] O Repositório que a PR está sendo enviada é o [**dbinclui-org/dbinclui-backend**](https://github.com/dbinclui-org/dbinclui-backend)
- [ ] Foi realizado os testes unitários *
- [ ] Foi realizado os testes de integração *
- [ ] Foi adicionada as respectivas **labels**
- [x] A PR foi assinada

2022-01-11 16:35 UTC, eduardoaraya requested changes

2022-01-11 16:35 UTC, eduardoaraya commented on src/app/middlewares/validator/CategoriesValidator.ts
> +}
Não seria legal abstrairmos essa lógica pra um arquivo separado ? Ela é utilizada em todas as validações praticamente é um middleware default para as validações.

2022-01-11 16:47 UTC, eduardoaraya commented on tsconfig.json
> +      "@middlewares/*": ["./src/app/middlewares/*"],
Precisamos alterar nas configurações do `jest` também. No arquivo `jest.config.ts`. 

```
moduleNameMapper: {
    '@controllers/(.*)': ['<rootDir>/src/app/controllers/$1'],
    '@entities/(.*)': ['<rootDir>/src/app/entities/$1'],
    '@middlewares/(.*)': ['<rootDir>/src/app/middlewares/$1'],  // ---> Alterar aqui tbm
    '@models/(.*)': ['<rootDir>/src/app/models/$1'],
    '@repositories/(.*)': ['<rootDir>/src/app/repositories/$1'],
    '@routes/(.*)': ['<rootDir>/src/app/routes/$1'],
  },

2022-01-11 19:44 UTC, Antonia095 commented
Ajustes realizados como solicitado!

2022-01-12 11:42 UTC, fabiojcbatista commented on src/app/middlewares/validator/CategoriesValidator.ts
> +}
Sim ficou legal!!! Não precisa implementar a mesma funcionalidade a cada chamada de validação. Separamos como recomendado.

2022-01-12 12:33 UTC, eduardoaraya approved these changes

2022-01-12 12:45 UTC, LizSantana approved these changes

2022-01-12 12:47 UTC, Nicolasgbdas approved these changes

2022-01-12 12:47 UTC, merged