Feature/DBI-54 - Abstração conexão MongoDB e melhor .env
dbinclui-org/dbinclui-backend pull request #7
Opened 2021-12-17 19:20 UTC by arthurvergacas

Como o @eduardoaraya pediu, a gente mudou a forma de lidar com o .env para que ele possa ser definido programaticamente.

### Mas atenção!! :exclamation: 

Agora pra definir variável de ambiente é um pouco diferente. As mensagens de erro que a gente adicionou devem ajudar a resolver todos os problemas que vocês encontrarem, mas só pra garantir aqui vai uma explicação rápida do que fazer:

- #### Defina a variável de ambiente `NODE_ENV` na sua máquina. 
  - Isso não deve ser muito difícil, mas se algo der errado [essa resposta no stackoverflow](https://stackoverflow.com/a/11104156) pode ajudar.
- #### Crie a pasta `environments`, assim como seus conteúdos, na raiz do seu projeto 
  - Arquivos `.env` normalmente contêm informação sensível, e por isso não queremos que eles fiquem disponíveis na internet. Por isso, nós mesmo precisamos criá-los nos nossos computadores. Para nos ajudar a saber qual é a estrutura do `.env` existe o arquivo `.env.sample`. Nele você encontra as variáveis que devem ser definidas nos seus arquivos `.env.dev` e `.env.prod` dentro da pasta `environments`.

Se ainda houver algum problema, só me chamar (@arthurvergacas) ou chamar a @LizSantana.

2021-12-18 14:43 UTC, eduardoaraya requested changes
Alterar branch base para develop. Só clicar em edit ali perto do titulo da PR e alterar pra branch certa.

2021-12-18 15:09 UTC, eduardoaraya requested changes

2021-12-18 15:09 UTC, eduardoaraya commented on src/env.ts
> +if (process.env.NODE_ENV === 'development') {
Essa validação pode ser simplificada da seguinte forma:

```
(async function() {
  try {
     const envFile = process.env.NODE_ENV === 'production' ? '.env.prod' : '.env.dev'; 
     await dotenv.config({
        path: path.resolve('environments', envFile),
      });
  } catch(err) { 
    console.error(`
      Ocorreu um erro ao configurar o caminho para o arquivo '.env.dev'.
      Confirme que a pasta enviroments está configurada na raiz do projeto contendo o arquivo '.env.dev'. 
    `);
  }
})()
```

2021-12-18 15:09 UTC, eduardoaraya commented on src/index.ts
> +app.listen(process.env.PORT || 3000, () => {
Adicionar a porta a uma variável:

```
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`servidor rodando na porta ${PORT}`);
});
```

2021-12-20 13:20 UTC, arthurvergacas commented
Agr eu n to em casa com o computador pra arrumarr, mas já já eu chego e resolvo os conflitos e mudo pra essa solução aí do ternario
talvez n consiga chegar em casa e arrumar a tempo da daily mas enfim dois clique resolve

2021-12-20 19:05 UTC, arthurvergacas commented
agora sim finalmente dps de 293819283 anos tentando resolver
agr os branchs estao iguais com os arquivos iguais e tudo igual perfeito maravilhoso

2021-12-20 19:11 UTC, arthurvergacas commented
mas pensando bem ainda n da pra dar merge ne
tem que fazer o unit teste de conexao
fzr isso entao

2021-12-20 19:14 UTC, AndersonMoura333 approved these changes, later dismissed

2021-12-20 20:37 UTC, eduardoaraya submitted a review, later dismissed

2021-12-20 20:52 UTC, eduardoaraya approved these changes

2021-12-20 20:52 UTC, eduardoaraya approved these changes

2021-12-20 21:20 UTC, LizSantana approved these changes

2021-12-20 21:22 UTC, AndersonMoura333 approved these changes

2021-12-20 21:42 UTC, merged