Feature/DBI-US005-19 - Nova rota/controller/validaçao para update do guia
dbinclui-org/dbinclui-backend pull request #73
Opened 2022-01-24 20:21 UTC by LizSantana

## Descrição

Foi criada a rota para o update do dia e as funções nelas utilizadas no controller, repositório e validação. E seus testes respectivos.

____

**Link do card:**
[Nova rota/controller/validaçao para update do guia](https://trello.com/c/ugUXjxv8/19-6us005-back-nova-rota-controller-valida%C3%A7ao-para-update-do-guia)

____

## Checklist Code Review
Avaliar se todos os itens a seguir foram feitos. Os itens com `*` não são obrigatórios.

- [ ] Foi adicionada a descrição da PR
- [ ] Foi adicionado o link do card
- [ ] A branch segue o padrão com o prefixo DBI
- [ ] Está seguindo os padrões de prefixo do gitflow (feature, bugfix, hotfix, release)
- [ ] O título da PR segue o padrão: ***Nome da branch - Título do card***
- [ ] A PR está sendo enviada para a branch `develop`
- [ ] O Repositório que a PR está sendo enviada é o [**dbinclui-org/dbinclui-backend**](https://github.com/dbinclui-org/dbinclui-backend)
- [ ] Foi realizado os testes unitários *
- [ ] Foi realizado os testes de integração *
- [ ] Foi adicionada as respectivas **labels**
- [ ] A PR foi assinada

2022-01-24 21:08 UTC, fabiojcbatista reviewed
Comment

2022-01-24 21:08 UTC, fabiojcbatista commented on src/app/controllers/GuidesController.ts
> +      res.status(200).json({ data: guides });
Trocar o retorno da Função para exibir o valor atualizado no Retorno da Rota
![imagem](https://user-images.githubusercontent.com/88551779/150864971-a07c0c17-fb8e-42d3-8cc0-45cae6d0407d.png)

2022-01-24 21:10 UTC, fabiojcbatista requested changes

2022-01-24 21:10 UTC, fabiojcbatista commented on src/app/routes/guides-router.ts
> +  router.post('/update/:id', GuidesController.updateGuide),
Trocar router.post para: router.put

2022-01-25 16:30 UTC, fabiojcbatista approved these changes

2022-01-25 17:12 UTC, NicoleSF approved these changes

2022-01-25 19:00 UTC, ketrynsdm approved these changes

2022-01-25 19:02 UTC, merged