Feature/DBI-57 - Estrutura de rotas
dbinclui-org/dbinclui-backend pull request #8
Opened 2021-12-17 20:45 UTC by nickolasL13

2021-12-17 20:48 UTC, fabiojcbatista approved these changes, later dismissed
ok

2021-12-17 20:48 UTC, mgunnar approved these changes, later dismissed

2021-12-17 21:00 UTC, arthurvergacas requested changes

2021-12-17 21:00 UTC, arthurvergacas commented on src/app/routes/routes.ts
> +  res.status(200).json({message: "Ish, nada aqui O.o"});
Será que não era melhor retornar com um 404??

2021-12-17 21:07 UTC, AndersonMoura333 approved these changes, later dismissed

2021-12-20 19:14 UTC, AndersonMoura333 approved these changes

2021-12-20 20:43 UTC, arthurvergacas approved these changes

2021-12-20 20:44 UTC, merged