feature/DBI-US013-68 - Nova rota/controller/validaçao para update do conteúdo digital
dbinclui-org/dbinclui-backend pull request #92
Opened 2022-02-03 14:46 UTC by roazambuja

## Descrição

Foi criada a rota, o controller e a lógica de validação para o update de um conteúdo digital. Também realizamos os testes do repositório e do validator. 

____

**Link do card:**
[[US013] BACK - Nova rota/controller/validaçao para update do conteúdo digital](https://trello.com/c/k1r3E2E9/68-6us013-back-nova-rota-controller-valida%C3%A7ao-para-update-do-conte%C3%BAdo-digital)

____

## Checklist Code Review
Avaliar se todos os itens a seguir foram feitos. Os itens com `*` não são obrigatórios.

- [ ] Foi adicionada a descrição da PR
- [ ] Foi adicionado o link do card
- [ ] A branch segue o padrão com o prefixo DBI
- [ ] Está seguindo os padrões de prefixo do gitflow (feature, bugfix, hotfix, release)
- [ ] O título da PR segue o padrão: ***Nome da branch - Título do card***
- [ ] A PR está sendo enviada para a branch `develop`
- [ ] O Repositório que a PR está sendo enviada é o [**dbinclui-org/dbinclui-backend**](https://github.com/dbinclui-org/dbinclui-backend)
- [ ] Foi realizado os testes unitários *
- [ ] Foi realizado os testes de integração *
- [ ] Foi adicionada as respectivas **labels**
- [ ] A PR foi assinada

2022-02-03 14:57 UTC, mgunnar approved these changes

2022-02-03 15:23 UTC, Nicolasgbdas approved these changes

2022-02-03 19:04 UTC, LizSantana requested changes
Terminar os testes de updateDigitalContents do controller

2022-02-04 17:55 UTC, LizSantana approved these changes

2022-02-04 17:57 UTC, brunomdrrosa approved these changes

2022-02-04 17:58 UTC, merged